services:
  - type: web
    name: management-library
    env: php
    plan: free
    buildCommand: "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && php artisan config:cache && php artisan route:cache"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_NAME
        value: "Management Library"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://management-library.onrender.com
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromService:
          type: pserv
          name: mysql
          property: database
      - key: DB_USERNAME
        fromService:
          type: pserv
          name: mysql
          property: username
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: mysql
          property: password

  - type: pserv
    name: mysql
    env: mysql
    plan: free
    disk:
      name: data
      mountPath: /var/lib/mysql
      sizeGB: 1 